# Generated by Django 4.2.7 on 2026-01-14 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillanalysis',
            options={'ordering': ['-analyzed_at'], 'verbose_name_plural': 'Skill Analyses'},
        ),
        migrations.AddField(
            model_name='skillanalysis',
            name='partially_matched_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='skillanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='skillanalysis',
            name='gap_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='skillanalysis',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analyzer.job'),
        ),
        migrations.AlterField(
            model_name='skillanalysis',
            name='match_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='skillanalysis',
            name='matched_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skillanalysis',
            name='missing_skills',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='skillanalysis',
            name='readiness_level',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('JOB_READY', 'Job Ready'), ('HIGHLY_COMPATIBLE', 'Highly Compatible')], default='BEGINNER', max_length=20),
        ),
        migrations.AlterField(
            model_name='skillanalysis',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='analyzer.resume'),
        ),
    ]
