# Generated by Django 4.2.7 on 2026-01-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
